Feature: Arrays Practice

  @no-clobber
  Scenario: Practice with Arrays
    Given the file '../methods_and_recursion/bottles_of_beer.rb' exists and is executable
    And I run `../methods_and_recursion/bottles_of_beer.rb`

    Then I should see the lyric for 99 bottles of beer
    And I should see the lyric for 98 bottles of beer
    And I should see the lyric for 97 bottles of beer
    And I should see the lyric for 96 bottles of beer
    And I should see the lyric for 95 bottles of beer
    And I should see the lyric for 94 bottles of beer
    And I should see the lyric for 93 bottles of beer
    And I should see the lyric for 92 bottles of beer
    And I should see the lyric for 91 bottles of beer
    And I should see the lyric for 90 bottles of beer
    And I should see the lyric for 89 bottles of beer
    And I should see the lyric for 88 bottles of beer
    And I should see the lyric for 87 bottles of beer
    And I should see the lyric for 86 bottles of beer
    And I should see the lyric for 85 bottles of beer
    And I should see the lyric for 84 bottles of beer
    And I should see the lyric for 83 bottles of beer
    And I should see the lyric for 82 bottles of beer
    And I should see the lyric for 81 bottles of beer
    And I should see the lyric for 80 bottles of beer
    And I should see the lyric for 79 bottles of beer
    And I should see the lyric for 78 bottles of beer
    And I should see the lyric for 77 bottles of beer
    And I should see the lyric for 76 bottles of beer
    And I should see the lyric for 75 bottles of beer
    And I should see the lyric for 74 bottles of beer
    And I should see the lyric for 73 bottles of beer
    And I should see the lyric for 72 bottles of beer
    And I should see the lyric for 71 bottles of beer
    And I should see the lyric for 70 bottles of beer
    And I should see the lyric for 69 bottles of beer
    And I should see the lyric for 68 bottles of beer
    And I should see the lyric for 67 bottles of beer
    And I should see the lyric for 66 bottles of beer
    And I should see the lyric for 65 bottles of beer
    And I should see the lyric for 64 bottles of beer
    And I should see the lyric for 63 bottles of beer
    And I should see the lyric for 62 bottles of beer
    And I should see the lyric for 61 bottles of beer
    And I should see the lyric for 60 bottles of beer
    And I should see the lyric for 59 bottles of beer
    And I should see the lyric for 58 bottles of beer
    And I should see the lyric for 57 bottles of beer
    And I should see the lyric for 56 bottles of beer
    And I should see the lyric for 55 bottles of beer
    And I should see the lyric for 54 bottles of beer
    And I should see the lyric for 53 bottles of beer
    And I should see the lyric for 52 bottles of beer
    And I should see the lyric for 51 bottles of beer
    And I should see the lyric for 50 bottles of beer
    And I should see the lyric for 49 bottles of beer
    And I should see the lyric for 48 bottles of beer
    And I should see the lyric for 47 bottles of beer
    And I should see the lyric for 46 bottles of beer
    And I should see the lyric for 45 bottles of beer
    And I should see the lyric for 44 bottles of beer
    And I should see the lyric for 43 bottles of beer
    And I should see the lyric for 42 bottles of beer
    And I should see the lyric for 41 bottles of beer
    And I should see the lyric for 40 bottles of beer
    And I should see the lyric for 39 bottles of beer
    And I should see the lyric for 38 bottles of beer
    And I should see the lyric for 37 bottles of beer
    And I should see the lyric for 36 bottles of beer
    And I should see the lyric for 35 bottles of beer
    And I should see the lyric for 34 bottles of beer
    And I should see the lyric for 33 bottles of beer
    And I should see the lyric for 32 bottles of beer
    And I should see the lyric for 31 bottles of beer
    And I should see the lyric for 30 bottles of beer
    And I should see the lyric for 29 bottles of beer
    And I should see the lyric for 28 bottles of beer
    And I should see the lyric for 27 bottles of beer
    And I should see the lyric for 26 bottles of beer
    And I should see the lyric for 25 bottles of beer
    And I should see the lyric for 24 bottles of beer
    And I should see the lyric for 23 bottles of beer
    And I should see the lyric for 22 bottles of beer
    And I should see the lyric for 21 bottles of beer
    And I should see the lyric for 20 bottles of beer
    And I should see the lyric for 19 bottles of beer
    And I should see the lyric for 18 bottles of beer
    And I should see the lyric for 17 bottles of beer
    And I should see the lyric for 16 bottles of beer
    And I should see the lyric for 15 bottles of beer
    And I should see the lyric for 14 bottles of beer
    And I should see the lyric for 13 bottles of beer
    And I should see the lyric for 12 bottles of beer
    And I should see the lyric for 11 bottles of beer
    And I should see the lyric for 10 bottles of beer
    And I should see the lyric for 9 bottles of beer
    And I should see the lyric for 8 bottles of beer
    And I should see the lyric for 7 bottles of beer
    And I should see the lyric for 6 bottles of beer
    And I should see the lyric for 5 bottles of beer
    And I should see the lyric for 4 bottles of beer
    And I should see the lyric for 3 bottles of beer
    And I should see the lyric for 2 bottles of beer
    And I should see the lyric for 1 bottles of beer
    And I should see the lyric for 0 bottles of beer
